spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: password
    hikari:
      connection-timeout: 300
      maximum-pool-size: 5
  flyway:
    url: jdbc:postgresql://localhost:5432/db
    user: postgres
    password: password
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
jwt:
  secret: '3b1Uth9C312$@saed99gGCBfFv0lZq6PpUMJw'
  expirationMs: 10800000