create table public.users
(
    id       bigint generated by default as identity
        primary key,
    balance  double precision not null,
    email    varchar(255)     not null,
    password varchar(255)     not null,
    username varchar(255)     not null
        constraint uk_r43af9ap4edm43mmtq01oddj6
            unique
);

alter table public.users
    owner to postgres;