create table public.users_tokens
(
    id      bigint generated by default as identity
        primary key,
    token   varchar(255) not null
        constraint uk_dq6lcrvwx7fsg022qa8179i19
            unique,
    user_id bigint       not null
        constraint fk1xl95grn90nu35htsi9o5kbxw
            references public.users
);

alter table public.users_tokens
    owner to postgres;