create table public.products
(
    id           bigint generated by default as identity
        primary key,
    count        integer,
    description  varchar(255),
    organization varchar(255),
    price        double precision,
    title        varchar(255)
);

alter table public.products
    owner to postgres;

create table public.product_reviews
(
    product_id bigint not null
        constraint fk35kxxqe2g9r4mww80w9e3tnw9
            references public.products,
    reviews    varchar(255)
);

alter table public.product_reviews
    owner to postgres;

create table public.product_estimates
(
    product_id bigint not null
        constraint fk8elpvgd4af6yy4arhppn31qt3
            references public.products,
    estimates  integer
);

alter table public.product_estimates
    owner to postgres;

create table public.product_characteristics
(
    product_id          bigint       not null
        constraint fklwuvy71q239qxmgor4u6ni4ej
            references public.products,
    characteristics     varchar(255),
    characteristics_key varchar(255) not null,
    primary key (product_id, characteristics_key)
);

alter table public.product_characteristics
    owner to postgres;

